### ISSUE TITLE
Error: Not able to parse artifact type: undefined

### ISSUE THREAD

**Issue by nab-emre-inanli** [github/rally#199]
**Describe the bug**
Using a lowercase Rally Story Id in the pull request body is resulting in an exception.
"Error occurred while validating Rally Artifacts: Error: Not able to parse artifact type: undefined"

**To Reproduce**
1. Create a new PR
2. in the body of the PR add a Rally story usxxxx (lower case us) 
3. check the Rally integration details
4. see the error "Error occurred while validating Rally Artifacts: Error: Not able to parse artifact type: undefined"

**Expected behavior**
If this is considered an invalid Rally Story id, we should get a validation failed result rather than an exception.
The other option is making the check case insensitive.

**Screenshots**

**Additional context**
If you edit the PR body, and change the story id to upper case, this fixes the issue.

Here's my test config file:

```
---
# Name of the GitHub Check
checksName: integrations/rally

# Check PR Body for Rally story/defect (true | false)
checkPRBody: true

# Check PR Title for Rally story/defect (true | false)
checkPRTitle: false

# Check all commit messages for a Rally story/defect (true | false)
checkCommitMessages: false

# Set Rally Flow State to Complete on merge if the PR Body contains "/completes <DEFECT/STORY ID>"
mergeOnPRBody: true

# Comment on the PR in addition to the check message? (true | false)
commentOnPull: false

rally:
  server: https://rally1.rallydev.com
  workspace: xxxxxxxxxxx

  # Which projects this repo will link to.
  projects:
    - TEST Squad 1
    - TEST Squad 2

  # List of valid Rally objects to check
  objects:
    - defect
    - task
    - userstory
    - story

  # List of Rally states that an issue must be in in order to pass
  states:
    - Ready
    - Defined
    - In-Progress

```
