### ISSUE TITLE
Update CodeQL analysis to use new repository

### ISSUE THREAD

**Issue by robertbrignull** [github/rally#42]
I don't have write access to open a PR but here's how the [codeql.yml](https://github.com/github/rally/blob/master/.github/workflows/codeql.yml) file should look.
```yaml
name: "CodeQL analysis"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: github/codeql-action/init@v1
      with:
        languages: javascript
    - uses: github/codeql-action/analyze@v1
```

The bulk of this change is updating to use the new repository name and branch, so this repository will get up to date feature and bug fixes for the codeql-action and code scanning. I've also removed some unnecessary bits and configuration as we've streamlined the process a bit since the early days.
