### ISSUE TITLE
Consolidate rally config items

### ISSUE THREAD

**Issue by primetheus** [github/rally#85]
The present YAML file contains the following:

```yaml
rallyProjects: ['Sample Project', 'devops-engineering']
rallyObjects: ['defect', 'userstory']
artifactStatuses: ['Defined', 'In-Progress']
rally:
  server: https://rally1.rallydev.com
  #username: me
  #password: pass
  #api_key: key
  workspace: 12345
```

It would be better for organization to consolidate them into the following:

```yaml
rally:
  server: https://rally1.rallydev.com
  #username: me
  #password: pass
  #api_key: key
  workspace: 12345
  projects:
    - Sample Project
    - devops-engineering
  objects:
    - defect
    - userstory
  states:
    - Defined
    - In-Progress
```
